[tools]
go = "latest"
[tasks.build]
description = "Build"
run = "go build -o ./bin/displayfen ./cmd/displayfen/main.go"
[tasks.test]
description = "Test"
run = [
	"go test ./... -cover -coverprofile=coverage.out",
]
