on:
  push:
    branches:
      - "main"
    paths:
      - "**.go"
      - "**.mod"
  pull_request:
    branches:
      - "main"
    paths:
      - "**.go"
      - "**.mod"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
      - name: install mise
        uses: jdx/mise-action@v4
      - name: build code
        run: mise run build
      - name: upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: ${{github.workspace}}/bin
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
      - name: install mise
        uses: jdx/mise-action@v4
      - name: build code
        run: mise run test
